### ISSUE TITLE
Benchmarks too short?

### ISSUE THREAD

**Issue by mgeier** [tqtrungse/omango#6]
I did some timing measurements on your benchmarks (for non-blocking SPSC) and I found that only a small part of them measure the multi-threaded behavior of the queue.

Here are some timings that I measured:

The benchmarks include the time for the creation and initialization of the queue, but that's not a big deal, since that's less than 2 usec.

More importantly, it also measures the creation of the thread, which means that the main thread starts reading from the queue only after about 30 usec.

But the second thread is not fully running yet, it takes another 25 usec or so until it starts writing to the queue.

The actual parallel writing and reading then only takes 25 to 30 usec.

Closing the thread then also takes about 25 to 30 usec.

All in all, the parallel processing (which I guess is what we want to benchmark, right?) is only less than a third of the total time.

I think it would be better to increase the number of elements sent over the queue (at least by 10x, but maybe 100x), in order for most of the measured time to be actually spent during parallel processing.

What do you think?

**Comment by tqtrungse** [comment]
Thanks for suggestion. 

I think that you right. I will update benchmark soon. 

I have tried to edit with 102400 ops for SPSC (queue size: 1024).

My benchmark on MSI Core I7 - Win11: 

![Untitled](https://github.com/tqtrungse/omango/assets/37643577/d7fcdf41-5580-4c28-8086-8130f1c38ee3)

**Comment by mgeier** [comment]
Thanks, now the results are a bit more diverse, which makes sense. You might want to update the graphs in the README as well.

BTW, I'm getting also getting a similar warning as in your screenshot above:

```
Benchmarking SPSC-Nonblock/Omango/0: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.7s, enable flat sampling, or reduce sample count to 60.
```
